# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c705352a647764020dcafe41fb901814b6a7ef50278c52ede5a7705c6283ebf36f2d4136a588cf254a071e68e70d79ae67a9c03186c4ea27daf8146faa8a360

test:
  secret_key_base: 5e52e38ab34bc0e0b60ec0548f10ebf54e14c252d9b6a389209acd485e0885825f076987700a52e4658611e973667c8de2ccb7e9c943d02c4952d7419a96c371

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
